#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
WRITTEN_VAR=()    # GitHub variable NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it offers values already saved to %s as defaults.%s\n' "$ENV_FILE" "$RESET"
  pause "Ready to start?"
}

# stage "Name" announces a stage and shows progress. After the first stage it
# waits for Enter before clearing, so the previous stage's confirmations and
# warnings are read before they leave the screen.
stage() {
  (( _STAGE_INDEX > 0 )) && pause
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else false; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# _read reads one line like `read`, but aborts the wizard when input ends:
# nobody is answering, and a blank answer must not pass for a real one.
_read() {
  if ! read "$@"; then
    printf '\n'
    warn "input ended before the wizard finished; run it in an interactive terminal"
    exit 1
  fi
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  _read -r _
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  _read -r reply
  [[ "$reply" =~ ^[Yy] ]]
}

# _env_quote VALUE prints VALUE as a dotenv literal. Plain values stay bare;
# anything with spaces, `#`, quotes, `$`, or backslashes is single-quoted
# (literal in dotenv loaders), or double-quoted with escapes if it contains a
# single quote. Without this, `abc#def` loads as `abc`.
_env_quote() {
  local value="$1"
  if [[ -n "$value" && "$value" =~ ^[A-Za-z0-9_./:@+=-]+$ ]]; then
    printf '%s' "$value"
  elif [[ "$value" != *"'"* ]]; then
    printf "'%s'" "$value"
  else
    value="${value//\\/\\\\}"
    value="${value//\"/\\\"}"
    printf '"%s"' "$value"
  fi
}

# _existing KEY: current value of KEY in ENV_FILE, if any, decoded from the
# quoting that _env_quote applied, so re-runs compare and re-send the bare value.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line value; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  value="${line#*=}"
  if [[ "$value" =~ ^\'(.*)\'$ ]]; then
    value="${BASH_REMATCH[1]}"
  elif [[ "$value" =~ ^\"(.*)\"$ ]]; then
    value="${BASH_REMATCH[1]}"
    value="${value//\\\"/\"}"
    value="${value//\\\\/\\}"
  fi
  printf '%s' "$value"
}

# _prompt KEY "Prompt" [-s] reads a non-empty value into $KEY, offering the
# existing ENV_FILE value as the default on re-runs (Enter keeps it).
_prompt() {
  local key="$1" prompt="$2" flag="${3:-}" current input
  current=$(_existing "$key" || true)
  while true; do
    if [[ -n "$current" ]]; then
      printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
    else
      printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
    fi
    if [[ "$flag" == "-s" ]]; then _read -rs input; printf '\n'; else _read -r input; fi
    [[ -z "$input" && -n "$current" ]] && input="$current"
    [[ -n "$input" ]] && break
    warn "a value is required"
  done
  printf -v "$key" '%s' "$input"
}

# ask KEY "Prompt" reads a visible (non-secret) value into $KEY.
ask() { _prompt "$1" "$2"; }

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() { _prompt "$1" "$2" -s; }

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it owner-only;
# replaces any existing line in place, keeping the file's mode and any
# symlink). Idempotent. Warns once if the file is tracked or not ignored by git.
_ENV_IGNORE_CHECKED=""
write_env() {
  local key="$1" value="$2" tmp
  [[ -e "$ENV_FILE" ]] || (umask 077 && : > "$ENV_FILE")
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$(_env_quote "$value")" >> "$tmp"
  cat "$tmp" > "$ENV_FILE"
  rm -f "$tmp"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
  if [[ -z "$_ENV_IGNORE_CHECKED" ]] && git rev-parse --is-inside-work-tree >/dev/null 2>&1; then
    _ENV_IGNORE_CHECKED=1
    if ! git check-ignore -q "$ENV_FILE" 2>/dev/null; then
      warn "$ENV_FILE is not ignored by git; add it to .gitignore before committing"
    fi
  fi
}

# _gh_repo prints the OWNER/REPO that gh writes target (from the current
# directory's remote), so the human can see where secrets go.
_gh_repo() {
  gh repo view --json nameWithOwner -q .nameWithOwner 2>/dev/null || printf 'the current repository'
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s on %s\n' "$GREEN" "$RESET" "$name" "$(_gh_repo)"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      WRITTEN_VAR+=("$name")
      printf '  %s✓ set%s GitHub variable %s on %s\n' "$GREEN" "$RESET" "$name" "$(_gh_repo)"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish waits for Enter, clears, then shows a closing summary of everything
# configured.
finish() {
  pause
  _clear
  if (( ${#SKIPPED[@]} )); then
    printf '\n%s%s  ⚠ Setup finished with steps left to do%s\n' "$BOLD" "$YELLOW" "$RESET"
  else
    printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  fi
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  (( ${#WRITTEN_VAR[@]} ))    && note "set ${#WRITTEN_VAR[@]} GitHub variable(s): ${WRITTEN_VAR[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=1

banner "Stripe setup"

# ── Example stage: replace with your real steps ───────────────────────────
stage "Stripe: API keys"
say "We'll grab your Stripe test keys and store them for local dev + CI."
open_url "https://dashboard.stripe.com/test/apikeys"
step "On the API keys page, copy the Publishable key (starts pk_test_)."
ask STRIPE_PUBLISHABLE_KEY "Paste the publishable key:"
step "Click 'Reveal test key' on the Secret key row, then copy it."
ask_secret STRIPE_SECRET_KEY "Paste the secret key:"
write_env STRIPE_PUBLISHABLE_KEY "$STRIPE_PUBLISHABLE_KEY"
write_env STRIPE_SECRET_KEY "$STRIPE_SECRET_KEY"
set_secret STRIPE_SECRET_KEY "$STRIPE_SECRET_KEY"   # CI needs this one
# ──────────────────────────────────────────────────────────────────────────

finish
